package com.epam.finaltask.dao;

import com.epam.finaltask.dao.impl.PersistenceException;
import com.epam.finaltask.entity.Message;

import java.util.List;

/**
 * Interface that contains methods specific to DAO that works with messages.
 */
public interface MessageDao extends Dao<Message> {

    /**
     * Find messages by topic id.
     * @param topicId Id of the topic
     * @return Topic messages
     * @throws PersistenceException If SQLException is thrown
     */
    List<Message> findMessagesByTopicId(long topicId) throws PersistenceException;

    /**
     * Adds message to the database with data generated by database.
     * @param entity Message to add to the database
     * @return {@code true} if message was successfully added, else returns {@code false}
     * @throws PersistenceException If SQLException is thrown
     */
    boolean createWithGeneratedDate(Message entity) throws PersistenceException;

    /**
     * Counts all topic messages.
     * @param topicId Id of the topic
     * @return Topic message count
     * @throws PersistenceException If SQLException is thrown
     */
    int countMessagesByTopicId(long topicId) throws PersistenceException;

    /**
     * Return all messages from specified page.
     * @param topicId Id of the topic
     * @param startPage Page to get messages from
     * @param numberOfMessagesPerPage Number of messages per page
     * @return All messages from chosen page
     * @throws PersistenceException If SQLException is thrown
     */
    List<Message> findPageMessages(long topicId, int startPage, int numberOfMessagesPerPage)
            throws PersistenceException;
}
