package com.epam.finaltask.dao;

import com.epam.finaltask.dao.impl.PersistenceException;
import com.epam.finaltask.entity.Topic;

/**
 * Interface that contains methods specific to DAO that works with topics.
 */
public interface TopicDao extends Dao<Topic> {

    /**
     * Adds topic to the database with date generated by database.
     * @param entity Topic to add.
     * @return {@code true} if topic was successfully added, else returns {@code false}
     * @throws PersistenceException if SQLException is thrown
     */
    boolean createWithGeneratedDate(Topic entity) throws PersistenceException;

    /**
     * Finds topic by title.
     * @param title Topic title
     * @return Topic if it was found, else returns null
     * @throws PersistenceException If SQLException is thrown
     */
    Topic findTopicByTitle(String title) throws PersistenceException;
}
