package com.epam.finaltask.dao;

import com.epam.finaltask.dao.impl.PersistenceException;
import com.epam.finaltask.entity.Topic;

import java.util.List;

/**
 * Interface that contains methods specific to DAO that works with topics.
 */
public interface TopicDao extends Dao<Topic> {

    List<Topic> findTopicsByAccountId(long accountId) throws PersistenceException;

    /**
     * Adds topic to the database with date generated by database.
     * @param entity Topic to add.
     * @return {@code true} if topic was successfully added, else returns {@code false}
     * @throws PersistenceException if SQLException is thrown
     */
    boolean createWithGeneratedDate(Topic entity) throws PersistenceException;
}
